const inventory = [
    {
        "id": 1,
        "name": "EQV Super Starter Kit for Arduino UNO R3 - Uno R3 Breadboard / Step Motor / SG90 Servo / 1602 LCD / jumper Wire",
        "category": "Learning",
        "productStore": "AliExpress",
        "basePrice": 50238.47,
        "shipping": 0,
        "isEssential": false,
        "isEssential": true,
        "essentialRank": 3,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "Quantity: 1\nHigh-concerned chemical: None\nPackage: DIP\nis_customized: Yes\nDissipation Power: Starter Kit for Arduino\nSupply Voltage: Starter Kit for Arduino\nApplication: Computer\nType: Module\nBrand Name: EQV\nOrigin: Mainland China\nCondition: New\nOperating Temperature: Starter Kit for Arduino",
        "description": "",
        "images": [
            "images/tools/learning/1 - arduino starter kit/main_images/main-image-1.jpeg",
            "images/tools/learning/1 - arduino starter kit/main_images/main-image-2.jpeg",
            "images/tools/learning/1 - arduino starter kit/main_images/main-image-3.jpeg",
            "images/tools/learning/1 - arduino starter kit/main_images/main-image-4.jpeg",
            "images/tools/learning/1 - arduino starter kit/main_images/main-image-5.jpeg",
            "images/tools/learning/1 - arduino starter kit/main_images/main-image-6.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005008899839817.html?spm=a2g0o.detail.pcDetailTopMoreOtherSeller.10.a2d7x2PLx2PLm1&gps-id=pcDetailTopMoreOtherSeller&scm=1007.40050.354490.0&scm_id=1007.40050.354490.0&scm-url=1007.40050.354490.0&pvid=35230bba-9d75-4c4f-b592-0d77cf3cb61c&_t=gps-id:pcDetailTopMoreOtherSeller,scm-url:1007.40050.354490.0,pvid:35230bba-9d75-4c4f-b592-0d77cf3cb61c,tpp_buckets:668%232846%238114%231999&pdp_ext_f=%7B%22order%22%3A%222%22%2C%22eval%22%3A%221%22%2C%22sceneId%22%3A%2230050%22%2C%22fromPage%22%3A%22recommend%22%7D&pdp_npi=6%40dis%21NGN%21108103.85%2154051.93%21%21%21468.94%21234.47%21%402103835e17663171960734169ea88c%2112000047125064691%21rec%21NG%21%21ABXZ%211%210%21n_tag%3A-29910%3Bd%3A9c8cba1b%3Bm03_new_user%3A-29895&utparam-url=scene%3ApcDetailTopMoreOtherSeller%7Cquery_from%3A%7Cx_object_id%3A1005008899839817%7C_p_origin_prod%3A#nav-description",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 2,
        "name": "UNO R3 Development Board ATmega328P with USB Cable Compatible with Arduino IDE for Beginners DIY Projects",
        "category": "Learning",
        "productStore": "Shop1105002259 Store",
        "basePrice": 9817.47,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nPackage: SMD\nis_customized: Yes",
        "description": "",
        "images": [
            "images/tools/learning/2 - atmega/main_images/main-image-1.jpeg",
            "images/tools/learning/2 - atmega/main_images/main-image-2.jpeg",
            "images/tools/learning/2 - atmega/main_images/main-image-3.jpeg",
            "images/tools/learning/2 - atmega/main_images/main-image-4.jpeg",
            "images/tools/learning/2 - atmega/main_images/main-image-5.jpeg",
            "images/tools/learning/2 - atmega/main_images/main-image-6.jpeg",
            "images/tools/learning/2 - atmega/main_images/main-image-7.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005010279892996.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 3,
        "name": "40PIN 20PIN 10PIN Dupont Line Male to Male Female to Female Male to Female No Shell Jumper Wire Dupont Cable for Arduino DIY KIT",
        "category": "Learning",
        "productStore": "LUOMEI Store",
        "basePrice": 6108.85,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nModel Number: Dupont 2.54\nBrand Name: LUOHONGDA",
        "description": "",
        "images": [
            "images/tools/learning/3- jumper cables/main_images/main-image-1.jpeg",
            "images/tools/learning/3- jumper cables/main_images/main-image-2.jpeg",
            "images/tools/learning/3- jumper cables/main_images/main-image-3.jpeg",
            "images/tools/learning/3- jumper cables/main_images/main-image-4.jpeg",
            "images/tools/learning/3- jumper cables/main_images/main-image-5.jpeg",
            "images/tools/learning/3- jumper cables/main_images/main-image-6.jpeg",
            "images/tools/learning/3- jumper cables/main_images/main-image-7.jpeg",
            "images/tools/learning/3- jumper cables/main_images/main-image-8.jpeg",
            "images/tools/learning/3- jumper cables/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005005177170567.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 4,
        "name": "1-50PCS Micro SD Card Module TF Card Reader/writer SPI Interface With Level Conversion Chip for Arduino ARM AVR",
        "category": "Learning",
        "productStore": "YTF Technology",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "Battery Included: No\nHigh-concerned chemical: None\nCompatible With: ARDUINO",
        "description": "",
        "images": [
            "images/tools/learning/4 - SD Card Module/main_images/main-image-1.jpeg",
            "images/tools/learning/4 - SD Card Module/main_images/main-image-10.jpeg",
            "images/tools/learning/4 - SD Card Module/main_images/main-image-11.jpeg",
            "images/tools/learning/4 - SD Card Module/main_images/main-image-12.jpeg",
            "images/tools/learning/4 - SD Card Module/main_images/main-image-13.jpeg",
            "images/tools/learning/4 - SD Card Module/main_images/main-image-14.jpeg",
            "images/tools/learning/4 - SD Card Module/main_images/main-image-15.jpeg",
            "images/tools/learning/4 - SD Card Module/main_images/main-image-2.jpeg",
            "images/tools/learning/4 - SD Card Module/main_images/main-image-3.jpeg",
            "images/tools/learning/4 - SD Card Module/main_images/main-image-4.jpeg",
            "images/tools/learning/4 - SD Card Module/main_images/main-image-5.jpeg",
            "images/tools/learning/4 - SD Card Module/main_images/main-image-6.jpeg",
            "images/tools/learning/4 - SD Card Module/main_images/main-image-7.jpeg",
            "images/tools/learning/4 - SD Card Module/main_images/main-image-8.jpeg",
            "images/tools/learning/4 - SD Card Module/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005005094642611.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 5,
        "name": "1/2/5/10PCS DS3231 IIC Module Precision Clock Module DS3231SN DS3231M Memory Real Time 3.3V/5V For Raspberry Pi (no battery)",
        "category": "Learning",
        "productStore": "Science Education Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "Quantity: 10\nHigh-concerned chemical: None\nis_customized: Yes",
        "description": "",
        "images": [
            "images/tools/learning/5 - RTC Module/main_images/main-image-1.jpeg",
            "images/tools/learning/5 - RTC Module/main_images/main-image-2.jpeg",
            "images/tools/learning/5 - RTC Module/main_images/main-image-3.jpeg",
            "images/tools/learning/5 - RTC Module/main_images/main-image-4.jpeg",
            "images/tools/learning/5 - RTC Module/main_images/main-image-5.jpeg",
            "images/tools/learning/5 - RTC Module/main_images/main-image-6.jpeg",
            "images/tools/learning/5 - RTC Module/main_images/main-image-7.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005009723923695.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 6,
        "name": "1-10PCS WeMos D1 Mini TYPE-C/Micro USB ESP8266 ESP-12F CH340G V2 Module WiFi D1 Mini Development Board 3.3V With Pin For Arduino",
        "category": "Learning",
        "productStore": "Shop1102186190 Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nCondition: New\nType: Module",
        "description": "",
        "images": [
            "images/tools/learning/6 - WeMos Module/main_images/main-image-1.jpeg",
            "images/tools/learning/6 - WeMos Module/main_images/main-image-10.jpeg",
            "images/tools/learning/6 - WeMos Module/main_images/main-image-11.jpeg",
            "images/tools/learning/6 - WeMos Module/main_images/main-image-2.jpeg",
            "images/tools/learning/6 - WeMos Module/main_images/main-image-3.jpeg",
            "images/tools/learning/6 - WeMos Module/main_images/main-image-4.jpeg",
            "images/tools/learning/6 - WeMos Module/main_images/main-image-5.jpeg",
            "images/tools/learning/6 - WeMos Module/main_images/main-image-6.jpeg",
            "images/tools/learning/6 - WeMos Module/main_images/main-image-7.jpeg",
            "images/tools/learning/6 - WeMos Module/main_images/main-image-8.jpeg",
            "images/tools/learning/6 - WeMos Module/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005007877904928.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 7,
        "name": "4S 14.6V/16.8V PD 100W Charge/Discharge Integrated Module Ternary Lithium/Lithium Iron Phosphate 20V 5A Output Fast Charging",
        "category": "Learning",
        "productStore": "Electronics Kit Store",
        "basePrice": 8981.38,
        "shipping": 5935.61,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "None",
        "brief": "Quantity: 1\nHigh-concerned chemical: None\nPackage: SOP",
        "description": "",
        "images": [
            "images/tools/learning/7 - 4S 100W PD Board/main_images/main-image-1.jpeg",
            "images/tools/learning/7 - 4S 100W PD Board/main_images/main-image-2.jpeg",
            "images/tools/learning/7 - 4S 100W PD Board/main_images/main-image-3.jpeg",
            "images/tools/learning/7 - 4S 100W PD Board/main_images/main-image-4.jpeg",
            "images/tools/learning/7 - 4S 100W PD Board/main_images/main-image-5.jpeg",
            "images/tools/learning/7 - 4S 100W PD Board/main_images/main-image-6.jpeg",
            "images/tools/learning/7 - 4S 100W PD Board/main_images/main-image-7.jpeg",
            "images/tools/learning/7 - 4S 100W PD Board/main_images/main-image-8.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005010486167187.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 8,
        "name": "2025new Fast Charging 18650 Battery High Quality 9800mah 3.7V 18650 Li Ion Battery Flashlight Charging Battery",
        "category": "Learning",
        "productStore": "Original. Button Cell Store",
        "basePrice": 5295.06,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "None",
        "brief": "High-concerned chemical: None\nSize: 18650\nReplacement Battery: Yes",
        "description": "",
        "images": [
            "https://ae-pic-a1.aliexpress-media.com/kf/S44d05b7eb3a74f5bb41eeeef14db87c6w.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S47a227f4c768410c8ac164e977b0fe040.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S60b0a63f4b494c49aa3bad96c9cfe88aK.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sa9e88df543d04cd19d44275ca12afd22D.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S6855e18c332a4931ab4d0f9c85c4e2291.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sf0cfe2896673434ab5e7c6ae108720170.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sba90932a0afc422797d90305b9a26709R.png",
            "https://ae-pic-a1.aliexpress-media.com/kf/S8c12c3335aea4831a8b3da21fa9b71d92.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S60b0a63f4b494c49aa3bad96c9cfe88aK.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sa9e88df543d04cd19d44275ca12afd22D.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sa0a5f1e2ac6246f2a3616529cbed8a442.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S6855e18c332a4931ab4d0f9c85c4e2291.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Saddfca3179974b549756b5d91f0cffadO.png",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sb85bfcd9196c47bb878717d6fa8c871an.png",
            "https://ae-pic-a1.aliexpress-media.com/kf/S75b7b300e9ab4935b85a86349ff94b2aL.png",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sc581b9b5aa614ff9897f854fc3a893184.png",
            "https://ae-pic-a1.aliexpress-media.com/kf/S1fdbadc19895498cb104774c8e4f3a9bl.png",
            "https://ae-pic-a1.aliexpress-media.com/kf/S92a92157f1264928a5fde8378cbe6a55F.png",
            "https://ae-pic-a1.aliexpress-media.com/kf/S4d32fe96a3624563804b045ebc6e783aZ.png"
        ],
        "productLink": "https://www.aliexpress.com/item/1005009885144731.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 9,
        "name": "CS1W DIY 40x18650 Power Storage Box, DIY Power Case Box with LED Lights Case Support PD Charging/Wireless Charging Functions",
        "category": "Learning",
        "productStore": "Shop1104299567 Store",
        "basePrice": 9024.23,
        "shipping": 26970.12,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "None",
        "brief": "Item Type: DIY Box & Shell\nOrigin: Mainland China",
        "description": "",
        "images": [
            "images/tools/learning/9 - case/main_images/main-image-1.jpeg",
            "images/tools/learning/9 - case/main_images/main-image-10.jpeg",
            "images/tools/learning/9 - case/main_images/main-image-11.jpeg",
            "images/tools/learning/9 - case/main_images/main-image-2.jpeg",
            "images/tools/learning/9 - case/main_images/main-image-3.jpeg",
            "images/tools/learning/9 - case/main_images/main-image-4.jpeg",
            "images/tools/learning/9 - case/main_images/main-image-5.jpeg",
            "images/tools/learning/9 - case/main_images/main-image-6.jpeg",
            "images/tools/learning/9 - case/main_images/main-image-7.jpeg",
            "images/tools/learning/9 - case/main_images/main-image-8.jpeg",
            "images/tools/learning/9 - case/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005010227573864.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 10,
        "name": "10-100PCS 18650 battery 3.7V 6800mAh lithium-ion rechargeable battery pointed flashlight toy remote control is the TOP STORE",
        "category": "Learning",
        "productStore": "MYWAY Digital Store",
        "basePrice": 15753.6,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "None",
        "brief": "High-concerned chemical: None\nBattery Number: 1~10\nSize: 18650",
        "description": "",
        "images": [
            "https://ae-pic-a1.aliexpress-media.com/kf/S1df1511484484588896d3d41d64c6c6dm.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sbca3583ccfa6473196f746720120115d1.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S1c2e13243d044d6497fe9220d0474130j.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sb083de46d5304ea192715718190dd961H.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sda22c668326541e7990ee509c5b190be1.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S5f0ff1e8bc534471b639bd337b5b7e61u.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S093031a5293a47859dc4aada26e6688f2.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S223cecf692664649bfac8b9d551881e7P.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S0034c7a504664d76a57ed4d6cf1b7bfcD.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sf2323a9c4d8b4d6bbf5a414d88f59befY.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S800434abef5e4af29f22737fc5b61132w.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Saeed59d7c2de4e8db6b7ff0dcaa6cf20n.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S8c2f3ddcc7f5487f930020785fdeb8bde.jpg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005010049705208.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 11,
        "name": "Toocki 240W Type C to Type C Cable PD3.1 Digital Display 100W Fast Charging USB C Cable for Macbook iPhone 16 15 Samsung Xiaomi",
        "category": "Learning",
        "productStore": "toocki Direct Official Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae-pic-a1.aliexpress-media.com/kf/S7da057dcd6e8423da216398874e6dcdbb.png",
        "brief": "High-concerned chemical: None\nMaterial: Braid\nConnector B: Type-C",
        "description": "",
        "images": [
            "images/tools/learning/11 - 240W USB-C Cable/main_images/main-image-1.jpeg",
            "images/tools/learning/11 - 240W USB-C Cable/main_images/main-image-2.jpeg",
            "images/tools/learning/11 - 240W USB-C Cable/main_images/main-image-3.jpeg",
            "images/tools/learning/11 - 240W USB-C Cable/main_images/main-image-4.jpeg",
            "images/tools/learning/11 - 240W USB-C Cable/main_images/main-image-5.jpeg",
            "images/tools/learning/11 - 240W USB-C Cable/main_images/main-image-6.jpeg",
            "images/tools/learning/11 - 240W USB-C Cable/main_images/main-image-7.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005008590867780.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 12,
        "name": "80W Super Fast Charge GaN USB-C Charging Head Fast Charger With Built-in PD 3.0 TypeC Cable For Iphone 16 15 Samsung With Light",
        "category": "Learning",
        "productStore": "HOOFUN Factory Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": true,
        "essentialRank": 5,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nIntelligent Charge: No\nDisplay screen: No",
        "description": "",
        "images": [
            "images/tools/learning/12 - 80W Brick/main_images/main-image-1.jpeg",
            "images/tools/learning/12 - 80W Brick/main_images/main-image-10.jpeg",
            "images/tools/learning/12 - 80W Brick/main_images/main-image-11.jpeg",
            "images/tools/learning/12 - 80W Brick/main_images/main-image-12.jpeg",
            "images/tools/learning/12 - 80W Brick/main_images/main-image-13.jpeg",
            "images/tools/learning/12 - 80W Brick/main_images/main-image-14.jpeg",
            "images/tools/learning/12 - 80W Brick/main_images/main-image-2.jpeg",
            "images/tools/learning/12 - 80W Brick/main_images/main-image-5.jpeg",
            "images/tools/learning/12 - 80W Brick/main_images/main-image-7.jpeg",
            "images/tools/learning/12 - 80W Brick/main_images/main-image-8.jpeg",
            "images/tools/learning/12 - 80W Brick/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005009732718989.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 13,
        "name": "JCD 8898 Soldering Station 750W 2 in 1 Soldering Iron Hot Air Gun Rework Welding Station For Phone BGA SMD Welding Repair Tools",
        "category": "Repair",
        "productStore": "JCD Official Store",
        "basePrice": 55120.3,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "None",
        "brief": "High-concerned chemical: None\nOrigin: Mainland China\nModel Number: 8898",
        "description": "",
        "images": [
            "images/tools/repair/1 - SMD Station/main_images/main-image-1.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-10.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-11.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-12.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-13.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-14.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-15.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-16.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-17.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-18.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-19.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-2.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-20.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-3.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-4.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-5.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-6.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-7.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-8.jpeg",
            "images/tools/repair/1 - SMD Station/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005006123703131.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 14,
        "name": "Toolour LCD Soldering Iron Kit with Adjustable Temp 180-520°C/356~932℉ Auto Send Tin Soldering Iron Gun for Welding Repair",
        "category": "Repair",
        "productStore": "Toolour Store",
        "basePrice": 26441.27,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nIs Smart Device: No\nOrigin: Mainland China",
        "description": "",
        "images": [
            "images/tools/repair/2 - soldering Gun/main_images/main-image-1.jpeg",
            "images/tools/repair/2 - soldering Gun/main_images/main-image-2.jpeg",
            "images/tools/repair/2 - soldering Gun/main_images/main-image-3.jpeg",
            "images/tools/repair/2 - soldering Gun/main_images/main-image-4.jpeg",
            "images/tools/repair/2 - soldering Gun/main_images/main-image-5.jpeg",
            "images/tools/repair/2 - soldering Gun/main_images/main-image-6.jpeg",
            "images/tools/repair/2 - soldering Gun/main_images/main-image-7.jpeg",
            "images/tools/repair/2 - soldering Gun/main_images/main-image-8.jpeg",
            "images/tools/repair/2 - soldering Gun/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005008827631993.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 15,
        "name": "Cordless USB Digital Soldering Iron Adjustable Temperature 300-450℃ Type-C 1000mAh Battery Intelligent Solder Welding Iron Tool",
        "category": "Repair",
        "productStore": "JCD Official Store",
        "basePrice": 6544.83,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nIs Smart Device: Yes\nOrigin: Mainland China",
        "description": "",
        "images": [
            "images/tools/repair/3 - Cordless Soldering Iron/main_images/main-image-1.jpeg",
            "images/tools/repair/3 - Cordless Soldering Iron/main_images/main-image-10.jpeg",
            "images/tools/repair/3 - Cordless Soldering Iron/main_images/main-image-11.jpeg",
            "images/tools/repair/3 - Cordless Soldering Iron/main_images/main-image-12.jpeg",
            "images/tools/repair/3 - Cordless Soldering Iron/main_images/main-image-13.jpeg",
            "images/tools/repair/3 - Cordless Soldering Iron/main_images/main-image-2.jpeg",
            "images/tools/repair/3 - Cordless Soldering Iron/main_images/main-image-3.jpeg",
            "images/tools/repair/3 - Cordless Soldering Iron/main_images/main-image-4.jpeg",
            "images/tools/repair/3 - Cordless Soldering Iron/main_images/main-image-5.jpeg",
            "images/tools/repair/3 - Cordless Soldering Iron/main_images/main-image-6.jpeg",
            "images/tools/repair/3 - Cordless Soldering Iron/main_images/main-image-7.jpeg",
            "images/tools/repair/3 - Cordless Soldering Iron/main_images/main-image-8.jpeg",
            "images/tools/repair/3 - Cordless Soldering Iron/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005008350198853.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 16,
        "name": "Lead-free No-clean High Purity Solder Wire Tin Melting Point 217 Degrees Solder Wire for Electronic Repair Sn99.3cu0.7",
        "category": "Repair",
        "productStore": "HAOXPNG Tools Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nWeight: 20g/50g\nMaterial: Tin",
        "description": "",
        "images": [
            "https://ae-pic-a1.aliexpress-media.com/kf/S53237807c099485b9fd9c7a08944e288U.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S53237807c099485b9fd9c7a08944e288U.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S86dc26f568494d52930d62999e3efec48.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sc72ad501e9a04d0d9dd1e9951c368b78v.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S35f524b51d9a4aa6a6f14ef033997aba3.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S2b35e5cf0f72441a8476670447f28d8ag.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sbd24a5e277dd473190d8497b51c4d4362.jpg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005008563576114.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 17,
        "name": "Desoldering Braid Copper Mesh 8/15M Resistant Oxidation Low Residue for Computer PCB Circuit Board Repair Tool Tin Welding Wire",
        "category": "Repair",
        "productStore": "Shinevien Store",
        "basePrice": 8191.89,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nApplication: Flux for soldering\nWeight: 60g",
        "description": "",
        "images": [
            "images/tools/repair/5 - Braids/main_images/main-image-1.jpeg",
            "images/tools/repair/5 - Braids/main_images/main-image-2.jpeg",
            "images/tools/repair/5 - Braids/main_images/main-image-3.jpeg",
            "images/tools/repair/5 - Braids/main_images/main-image-4.jpeg",
            "images/tools/repair/5 - Braids/main_images/main-image-5.jpeg",
            "images/tools/repair/5 - Braids/main_images/main-image-6.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005007988716119.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 18,
        "name": "Aluminum Metal Desoldering Pump Suction Tin Gun Soldering Sucker Pen Removal Vacuum Soldering Iron Desolder Hand Welding Tools",
        "category": "Repair",
        "productStore": "ESPLB Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nis_customized: Yes\nModel Number: Desoldering Pump",
        "description": "",
        "images": [
            "images/tools/repair/6 - Pump/main_images/main-image-1 (1).jpeg",
            "images/tools/repair/6 - Pump/main_images/main-image-1.jpeg",
            "images/tools/repair/6 - Pump/main_images/main-image-2 (1).jpeg",
            "images/tools/repair/6 - Pump/main_images/main-image-2.jpeg",
            "images/tools/repair/6 - Pump/main_images/main-image-3 (1).jpeg",
            "images/tools/repair/6 - Pump/main_images/main-image-3.jpeg",
            "images/tools/repair/6 - Pump/main_images/main-image-4 (1).jpeg",
            "images/tools/repair/6 - Pump/main_images/main-image-4.jpeg",
            "images/tools/repair/6 - Pump/main_images/main-image-5 (1).jpeg",
            "images/tools/repair/6 - Pump/main_images/main-image-5.jpeg",
            "images/tools/repair/6 - Pump/main_images/main-image-6 (1).jpeg",
            "images/tools/repair/6 - Pump/main_images/main-image-6.jpeg",
            "images/tools/repair/6 - Pump/main_images/main-image-7 (1).jpeg",
            "images/tools/repair/6 - Pump/main_images/main-image-7.jpeg",
            "images/tools/repair/6 - Pump/main_images/main-image-8.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/32864628837.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 19,
        "name": "Sn99Ag0.3Cu0.7 Solder paste, flux, lead-free solder paste free cleaning is widely used in all kinds of soldering",
        "category": "Repair",
        "productStore": "PXAN Top-tier Tool Store Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nModel Number: HXP-603/HXP-604\nOrigin: Mainland China",
        "description": "",
        "images": [
            "images/tools/repair/7 - Flux/main_images/main-image-1.jpeg",
            "images/tools/repair/7 - Flux/main_images/main-image-10.jpeg",
            "images/tools/repair/7 - Flux/main_images/main-image-11.jpeg",
            "images/tools/repair/7 - Flux/main_images/main-image-12.jpeg",
            "images/tools/repair/7 - Flux/main_images/main-image-13.jpeg",
            "images/tools/repair/7 - Flux/main_images/main-image-14.jpeg",
            "images/tools/repair/7 - Flux/main_images/main-image-15.jpeg",
            "images/tools/repair/7 - Flux/main_images/main-image-16.jpeg",
            "images/tools/repair/7 - Flux/main_images/main-image-2.jpeg",
            "images/tools/repair/7 - Flux/main_images/main-image-3.jpeg",
            "images/tools/repair/7 - Flux/main_images/main-image-4.jpeg",
            "images/tools/repair/7 - Flux/main_images/main-image-5.jpeg",
            "images/tools/repair/7 - Flux/main_images/main-image-6.jpeg",
            "images/tools/repair/7 - Flux/main_images/main-image-7.jpeg",
            "images/tools/repair/7 - Flux/main_images/main-image-8.jpeg",
            "images/tools/repair/7 - Flux/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005009348891918.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 20,
        "name": "Soldering Iron Tip Tinner Activator Tip Cleaner Remover Lead Free 6g",
        "category": "Repair",
        "productStore": "HGKKXXLLD Store",
        "basePrice": 610.89,
        "shipping": 1757.43,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "None",
        "brief": "High-concerned chemical: None\nOrigin: Mainland China\nCertification: None",
        "description": "",
        "images": [
            "images/tools/repair/8 - sharpener/main_images/main-image-1.jpeg",
            "images/tools/repair/8 - sharpener/main_images/main-image-2.jpeg",
            "images/tools/repair/8 - sharpener/main_images/main-image-3.jpeg",
            "images/tools/repair/8 - sharpener/main_images/main-image-4.jpeg",
            "images/tools/repair/8 - sharpener/main_images/main-image-5.jpeg",
            "images/tools/repair/8 - sharpener/main_images/main-image-6.jpeg",
            "images/tools/repair/8 - sharpener/main_images/main-image-7.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005007443717612.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 21,
        "name": "Hayve 1600X USB Microscope 1080P HD Soldering Microscope with 8LEDs Compatible with Android, Mac, Windows (X4)",
        "category": "Repair",
        "productStore": "Hayve Official Store",
        "basePrice": 7392.14,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "Battery Included: No\nHigh-concerned chemical: None\nMagnification Ratio: 500X - 1500X",
        "description": "",
        "images": [
            "images/tools/repair/9 - Microscope/main_images/main-image-1.jpeg",
            "images/tools/repair/9 - Microscope/main_images/main-image-2.jpeg",
            "images/tools/repair/9 - Microscope/main_images/main-image-3.jpeg",
            "images/tools/repair/9 - Microscope/main_images/main-image-4.jpeg",
            "images/tools/repair/9 - Microscope/main_images/main-image-5.jpeg",
            "images/tools/repair/9 - Microscope/main_images/main-image-6.jpeg",
            "images/tools/repair/9 - Microscope/main_images/main-image-7.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005007428381572.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 22,
        "name": "14inch Portable Monitor 100%sRGB 2.2K 1400P FHD HDMI Type-C Travel Monitor External Second Computer Display for PC Mac Phone/PS",
        "category": "Repair",
        "productStore": "LANLIPU Select Store",
        "basePrice": 144636.17,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae-pic-a1.aliexpress-media.com/kf/S7da057dcd6e8423da216398874e6dcdbb.png",
        "brief": "High-concerned chemical: None\nScreen surface: MATT\nBracket Type: Ordinary Bracket",
        "description": "",
        "images": [
            "https://ae-pic-a1.aliexpress-media.com/kf/Sebf86d504c984482ac714d07f8db2e36m.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sebf86d504c984482ac714d07f8db2e36m.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S4ccebc85dc5444a0a1187a8665704b9bb.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sc61747a7f5564743b9911868468c6752w.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S87b0c1466d6940cc885754a33785de0ai.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sca1300bc1de14ad88e8bccb8fe99c4f5h.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S89c27cd434ba4511904557bc88a4e078f.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S4ccebc85dc5444a0a1187a8665704b9bb.jpg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005010027110454.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 23,
        "name": "Rafford 12Pcs Bendable Model Painting Alligator Clip Sticks Rubber Tips + Metal Magnetic Base - for Airbrush, Hobby Model Parts",
        "category": "Repair",
        "productStore": "AliExpress",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nOrigin: Mainland China",
        "description": "",
        "images": [
            "images/tools/repair/11 - hands/main_images/main-image-1.jpeg",
            "images/tools/repair/11 - hands/main_images/main-image-10.jpeg",
            "images/tools/repair/11 - hands/main_images/main-image-11.jpeg",
            "images/tools/repair/11 - hands/main_images/main-image-2.jpeg",
            "images/tools/repair/11 - hands/main_images/main-image-3.jpeg",
            "images/tools/repair/11 - hands/main_images/main-image-4.jpeg",
            "images/tools/repair/11 - hands/main_images/main-image-5.jpeg",
            "images/tools/repair/11 - hands/main_images/main-image-6.jpeg",
            "images/tools/repair/11 - hands/main_images/main-image-7.jpeg",
            "images/tools/repair/11 - hands/main_images/main-image-8.jpeg",
            "images/tools/repair/11 - hands/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005010089214223.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 24,
        "name": "Precision Screwdriver Set For Mobile Phones, Laptops, Tablets, And Computers, Suitable For Small Maintenance And Disassembly",
        "category": "Repair",
        "productStore": "Shop1103833657 Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nMaterial: Chrome Vanadium Steel\nType: Screwdrivers",
        "description": "",
        "images": [
            "images/tools/repair/12 - Phone Kit/main_images/main-image-1.jpeg",
            "images/tools/repair/12 - Phone Kit/main_images/main-image-10.jpeg",
            "images/tools/repair/12 - Phone Kit/main_images/main-image-11.jpeg",
            "images/tools/repair/12 - Phone Kit/main_images/main-image-2.jpeg",
            "images/tools/repair/12 - Phone Kit/main_images/main-image-3.jpeg",
            "images/tools/repair/12 - Phone Kit/main_images/main-image-4.jpeg",
            "images/tools/repair/12 - Phone Kit/main_images/main-image-5.jpeg",
            "images/tools/repair/12 - Phone Kit/main_images/main-image-6.jpeg",
            "images/tools/repair/12 - Phone Kit/main_images/main-image-7.jpeg",
            "images/tools/repair/12 - Phone Kit/main_images/main-image-8.jpeg",
            "images/tools/repair/12 - Phone Kit/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005009371533066.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 25,
        "name": "28/56 Grids Storage Box Portable DIY Diamond Painting Boxes Plastic Cases Jewelry Nail Art Rhinestone Beads Container Organizers",
        "category": "Repair",
        "productStore": "Shop1102882264 Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "Function: Reusable\nHigh-concerned chemical: None\nShape: Rectangle",
        "description": "",
        "images": [
            "images/tools/repair/13 - Plastic Box 1/main_images/main-image-1.jpeg",
            "images/tools/repair/13 - Plastic Box 1/main_images/main-image-2.jpeg",
            "images/tools/repair/13 - Plastic Box 1/main_images/main-image-4.jpeg",
            "images/tools/repair/13 - Plastic Box 1/main_images/main-image-5.jpeg",
            "images/tools/repair/13 - Plastic Box 1/main_images/main-image-6.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005007352339539.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 26,
        "name": "14pcs in 1 Set Beaded Storage Box Nail Art Jewelry Earring Seed Beads Storage Bottle DIY Diamond Painting Rhinestone Craft",
        "category": "Repair",
        "productStore": "Shop1103186880 Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "Function: Other\nHigh-concerned chemical: None\nShape: Rectangle",
        "description": "",
        "images": [
            "images/tools/repair/14 - Plastic Box 2/main_images/main-image-1.jpeg",
            "images/tools/repair/14 - Plastic Box 2/main_images/main-image-10.jpeg",
            "images/tools/repair/14 - Plastic Box 2/main_images/main-image-11.jpeg",
            "images/tools/repair/14 - Plastic Box 2/main_images/main-image-12.jpeg",
            "images/tools/repair/14 - Plastic Box 2/main_images/main-image-2.jpeg",
            "images/tools/repair/14 - Plastic Box 2/main_images/main-image-3.jpeg",
            "images/tools/repair/14 - Plastic Box 2/main_images/main-image-4.jpeg",
            "images/tools/repair/14 - Plastic Box 2/main_images/main-image-5.jpeg",
            "images/tools/repair/14 - Plastic Box 2/main_images/main-image-6.jpeg",
            "images/tools/repair/14 - Plastic Box 2/main_images/main-image-7.jpeg",
            "images/tools/repair/14 - Plastic Box 2/main_images/main-image-8.jpeg",
            "images/tools/repair/14 - Plastic Box 2/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005006939817574.html",
        "quantity": 2,
        "source": "AliExpress"
    },
    {
        "id": 27,
        "name": "10-11pcs ESD Tweezers Stainless Steel Precision Anti-Static Industrial Repair Tools Tweezers for Electronics Soldering Craft",
        "category": "Repair",
        "productStore": "FocusOnHome Shop Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nMaterial: Stainless steel\nOrigin: Mainland China",
        "description": "",
        "images": [
            "images/tools/repair/15 - tweezer set 1/main_images/main-image-1 (1).jpeg",
            "images/tools/repair/15 - tweezer set 1/main_images/main-image-1.jpeg",
            "images/tools/repair/15 - tweezer set 1/main_images/main-image-2 (1).jpeg",
            "images/tools/repair/15 - tweezer set 1/main_images/main-image-2.jpeg",
            "images/tools/repair/15 - tweezer set 1/main_images/main-image-3 (1).jpeg",
            "images/tools/repair/15 - tweezer set 1/main_images/main-image-3.jpeg",
            "images/tools/repair/15 - tweezer set 1/main_images/main-image-4 (1).jpeg",
            "images/tools/repair/15 - tweezer set 1/main_images/main-image-4.jpeg",
            "images/tools/repair/15 - tweezer set 1/main_images/main-image-5 (1).jpeg",
            "images/tools/repair/15 - tweezer set 1/main_images/main-image-5.jpeg",
            "images/tools/repair/15 - tweezer set 1/main_images/main-image-6.jpeg",
            "images/tools/repair/15 - tweezer set 1/main_images/main-image-7.jpeg",
            "images/tools/repair/15 - tweezer set 1/main_images/main-image-8.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005009466301297.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 28,
        "name": "MaAnt TC-01 TC-02 High Precision Insulation Ceramic Anti-magnetic Anti-Static Special Tweezers For Phone Flying Wire Repair",
        "category": "Repair",
        "productStore": "Mobile Phone Repair Tools Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nMaterial: Plastic\nOrigin: Mainland China",
        "description": "",
        "images": [
            "images/tools/repair/16 - tweezer set 2/main_images/main-image-1.jpeg",
            "images/tools/repair/16 - tweezer set 2/main_images/main-image-2.jpeg",
            "images/tools/repair/16 - tweezer set 2/main_images/main-image-3.jpeg",
            "images/tools/repair/16 - tweezer set 2/main_images/main-image-4.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005010363658329.html",
        "quantity": 1,
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 29,
        "name": "3-Piece Set of Wire Pliers, Diagonal Nose Pliers, Needle Nose Pliers, Industrial Grade Preferred Pliers, Durable Chromium Vanadium Steel, Suitable for Wire Cutting, Screwdriver, Etc",
        "category": "Repair",
        "productStore": "Best Tools For You Store",
        "basePrice": 18777.84,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nHandle Style: Bent\nFeatures: Multifunctional",
        "description": "",
        "images": [
            "https://ae-pic-a1.aliexpress-media.com/kf/S999e2f9840784cf7879f217166dda971T.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sf3ec6146ca18490a8269b7be3530a5e3m.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S76cc04cc523e4a78a4cb5cb39a63884bF.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sd7e898d1a1d3497a86631f6ba1a4016fB.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S37debce421c14bb99daf14b045265115E.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S63f3852d7ba340958a4d0f07288075d6a.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S3a273e222f8a46a7846e89029f9b6d8fg.jpg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005008598214515.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 30,
        "name": "Magnetic Mat Silicone Repair Mat Circuit Board Soldering Pad Heat Resistant 932°F Anti-Static for ESD Iron Phone Repair",
        "category": "Repair",
        "productStore": "Shop1103734903 Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nMaterial: Rubber\nType: Combination",
        "description": "",
        "images": [
            "images/tools/repair/18 - silicone mat/main_images/main-image-1.jpeg",
            "images/tools/repair/18 - silicone mat/main_images/main-image-10.jpeg",
            "images/tools/repair/18 - silicone mat/main_images/main-image-11.jpeg",
            "images/tools/repair/18 - silicone mat/main_images/main-image-12.jpeg",
            "images/tools/repair/18 - silicone mat/main_images/main-image-13.jpeg",
            "images/tools/repair/18 - silicone mat/main_images/main-image-14.jpeg",
            "images/tools/repair/18 - silicone mat/main_images/main-image-15.jpeg",
            "images/tools/repair/18 - silicone mat/main_images/main-image-16.jpeg",
            "images/tools/repair/18 - silicone mat/main_images/main-image-17.jpeg",
            "images/tools/repair/18 - silicone mat/main_images/main-image-18.jpeg",
            "images/tools/repair/18 - silicone mat/main_images/main-image-19.jpeg",
            "images/tools/repair/18 - silicone mat/main_images/main-image-2.jpeg",
            "images/tools/repair/18 - silicone mat/main_images/main-image-3.jpeg",
            "images/tools/repair/18 - silicone mat/main_images/main-image-4.jpeg",
            "images/tools/repair/18 - silicone mat/main_images/main-image-5.jpeg",
            "images/tools/repair/18 - silicone mat/main_images/main-image-6.jpeg",
            "images/tools/repair/18 - silicone mat/main_images/main-image-7.jpeg",
            "images/tools/repair/18 - silicone mat/main_images/main-image-8.jpeg",
            "images/tools/repair/18 - silicone mat/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005008040032049.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 31,
        "name": "PP Cutting Mat Workbench Patchwork Cut Pad Sewing Manual DIY Knife Engraving Leather Cutter Board Single Side Underlay",
        "category": "Repair",
        "productStore": "Shop1103885571 Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "Origin: Mainland China",
        "description": "",
        "images": [
            "images/tools/repair/19 - cutting mat/main_images/main-image-1.jpeg",
            "images/tools/repair/19 - cutting mat/main_images/main-image-2.jpeg",
            "images/tools/repair/19 - cutting mat/main_images/main-image-3.jpeg",
            "images/tools/repair/19 - cutting mat/main_images/main-image-4.jpeg",
            "images/tools/repair/19 - cutting mat/main_images/main-image-5.jpeg",
            "images/tools/repair/19 - cutting mat/main_images/main-image-6.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005007251692406.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 32,
        "name": "Bluetooth 5.4 Mouse Dual-Mode 2.4G Wireless Mouse 6 Buttons Gaming Mice Rechargeable Mouse 1600 DPI For PC Laptop Macbook",
        "category": "Productivity",
        "productStore": "Ton-Top Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nPower Type: Rechargeable\nNumber of Rollers: 1 pcs",
        "description": "",
        "images": [
            "images/tools/prod/1 - Wless Mouse/main_images/main-image-1 (1).jpeg",
            "images/tools/prod/1 - Wless Mouse/main_images/main-image-1.jpeg",
            "images/tools/prod/1 - Wless Mouse/main_images/main-image-2 (1).jpeg",
            "images/tools/prod/1 - Wless Mouse/main_images/main-image-2.jpeg",
            "images/tools/prod/1 - Wless Mouse/main_images/main-image-3 (1).jpeg",
            "images/tools/prod/1 - Wless Mouse/main_images/main-image-3.jpeg",
            "images/tools/prod/1 - Wless Mouse/main_images/main-image-4 (1).jpeg",
            "images/tools/prod/1 - Wless Mouse/main_images/main-image-4.jpeg",
            "images/tools/prod/1 - Wless Mouse/main_images/main-image-5 (1).jpeg",
            "images/tools/prod/1 - Wless Mouse/main_images/main-image-5.jpeg",
            "images/tools/prod/1 - Wless Mouse/main_images/main-image-6 (1).jpeg",
            "images/tools/prod/1 - Wless Mouse/main_images/main-image-6.jpeg",
            "images/tools/prod/1 - Wless Mouse/main_images/main-image-7 (1).jpeg",
            "images/tools/prod/1 - Wless Mouse/main_images/main-image-7.jpeg",
            "images/tools/prod/1 - Wless Mouse/main_images/main-image-8 (1).jpeg",
            "images/tools/prod/1 - Wless Mouse/main_images/main-image-8.jpeg",
            "images/tools/prod/1 - Wless Mouse/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005009212644441.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 33,
        "name": "MageGee Mini 60% Gaming Keyboard, RGB Backlit 61 Key Ultra-Compact Keyboard, TS91 Ergonomic Waterproof Mechanical Feeling Office",
        "category": "Productivity",
        "productStore": "MageGee Store",
        "basePrice": 15117.77,
        "shipping": 0,
        "isEssential": true,
        "essentialRank": 5,
        "dealTag": "https://ae-pic-a1.aliexpress-media.com/kf/S7da057dcd6e8423da216398874e6dcdbb.png",
        "brief": "High-concerned chemical: None\nSwitches Hot swap: No\nBacklight Type: Multicolor",
        "description": "",
        "images": [
            "images/tools/prod/2 - Wless Keys/main_images/main-image-1.jpeg",
            "images/tools/prod/2 - Wless Keys/main_images/main-image-2.jpeg",
            "images/tools/prod/2 - Wless Keys/main_images/main-image-3.jpeg",
            "images/tools/prod/2 - Wless Keys/main_images/main-image-4.jpeg",
            "images/tools/prod/2 - Wless Keys/main_images/main-image-5.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005007640318873.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 34,
        "name": "Wired Right Hand Vertical Mouse Ergonomic Gaming Mouse 800 1200 1600 DPI USB Optical Wrist Healthy Mice Mause For PC Computer",
        "category": "Productivity",
        "productStore": "Romantic month @ you Store",
        "basePrice": 14749.82,
        "shipping": 9210.66,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "None",
        "brief": "High-concerned chemical: None\nAcceleration: 20 G\nMovement speed, IPS: 60",
        "description": "",
        "images": [
            "https://ae-pic-a1.aliexpress-media.com/kf/He25c837b4e7a4b07bb53b76f2aa42de5q.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/H77cc535a8f1b42cca3945d18dadbe594M.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/H25fea7f9d5174b48bc82dd6c9ade3bfai.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Hb4e2c0478f3145fcbf5364e130bc8c77f.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/H71bc2b53c2834d3b8b8afd96edbcb013c.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sbe64d9a4b6e242749b63a01b3a9d5c49l.jpg"
        ],
        "productLink": "https://www.aliexpress.com/item/4000183436063.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 35,
        "name": "KM320 Keyboard And Mouse Set Waterproof Luminous Game Backlit Keyboard",
        "category": "Productivity",
        "productStore": "Shop1104203011 Store",
        "basePrice": 19447.99,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nType: ERGONOMIC\nBattery Included: No",
        "description": "",
        "images": [
            "https://ae-pic-a1.aliexpress-media.com/kf/Sc6c6be2e6975475abe0ace970eee9fbey.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S6e1278f955d2440ab73b9a3dce73fdbdS.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S5961d2c7e7594a8eb49ed2bc08ab9c559.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S523d4a67cc714f2995d9c1aae56651f4t.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Scbc44bbe58e443f58c088f80d45d26abS.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S4ba200450a924ae78fe945a388a71be9o.png",
            "https://ae-pic-a1.aliexpress-media.com/kf/S74f81e71c1264b41ad416e815ef257613.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S187883c6b0694162a5ec3874676b8a1cz.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S9db437331eac4ad4a58badcc343300dcJ.jpg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005007987300019.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 36,
        "name": "4K Webcam 1440P 2K Web Camera 1080P EMEET C60E Autofocus USB Computer Camera for Living/ Video Call/ Conference",
        "category": "Productivity",
        "productStore": "EMEET Tech Store",
        "basePrice": 32374.6,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae-pic-a1.aliexpress-media.com/kf/S7da057dcd6e8423da216398874e6dcdbb.png",
        "brief": "Auto Focus: Yes\nPackage: Yes\nInterface Type: USB",
        "description": "",
        "images": [
            "images/tools/prod/5 - camera/main_images/main-image-1.jpeg",
            "images/tools/prod/5 - camera/main_images/main-image-2.jpeg",
            "images/tools/prod/5 - camera/main_images/main-image-3.jpeg",
            "images/tools/prod/5 - camera/main_images/main-image-4.jpeg",
            "images/tools/prod/5 - camera/main_images/main-image-5.jpeg",
            "images/tools/prod/5 - camera/main_images/main-image-6.jpeg",
            "images/tools/prod/5 - camera/main_images/main-image-7.jpeg",
            "images/tools/prod/5 - camera/main_images/main-image-8.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005006702691545.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 37,
        "name": "Condenser Microphone USB Wired For PC Laptop Computer Professional Gaming Accessories Kit Gamer Sound Live Streaming Podcast RGB",
        "category": "Productivity",
        "productStore": "Future Dream Builder Store",
        "basePrice": 19999.88,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nBuilt-in Battery: No\nDiaphragm: S-Mall",
        "description": "",
        "images": [
            "images/tools/prod/6 - microphone/main_images/main-image-1.jpeg",
            "images/tools/prod/6 - microphone/main_images/main-image-2.jpeg",
            "images/tools/prod/6 - microphone/main_images/main-image-3.jpeg",
            "images/tools/prod/6 - microphone/main_images/main-image-4.jpeg",
            "images/tools/prod/6 - microphone/main_images/main-image-5.jpeg",
            "images/tools/prod/6 - microphone/main_images/main-image-6.jpeg",
            "images/tools/prod/6 - microphone/main_images/main-image-7.jpeg",
            "images/tools/prod/6 - microphone/main_images/main-image-8.jpeg",
            "images/tools/prod/6 - microphone/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005010572735123.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 38,
        "name": "Usb 8 In 1 Type C 3 1 To 4k HdTV Hub Adapter With Sd Tf Rj45 Card Reader Pd Fast Charge For Macbook Notebook Computer",
        "category": "Productivity",
        "productStore": "Shop1103815087 Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "Length: 15cm\nPackage: Yes\nFuntion: RJ45",
        "description": "",
        "images": [
            "images/tools/prod/7 - 8in1 Hub/main_images/main-image-1.jpeg",
            "images/tools/prod/7 - 8in1 Hub/main_images/main-image-2.jpeg",
            "images/tools/prod/7 - 8in1 Hub/main_images/main-image-3.jpeg",
            "images/tools/prod/7 - 8in1 Hub/main_images/main-image-4.jpeg",
            "images/tools/prod/7 - 8in1 Hub/main_images/main-image-5.jpeg",
            "images/tools/prod/7 - 8in1 Hub/main_images/main-image-6.jpeg",
            "images/tools/prod/7 - 8in1 Hub/main_images/main-image-7.jpeg",
            "images/tools/prod/7 - 8in1 Hub/main_images/main-image-8.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005005786590607.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 39,
        "name": "USB HUB 4/7 Ports USB 3.0 Cable Splitter With Power Switch 1 in 7 Out USB Extend Adapter Data Transmission Phone Charging Dock",
        "category": "Productivity",
        "productStore": "Shop1104998433 Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "Compatible PC Devices: Laptop\nHigh-concerned chemical: None\nPackage: Yes",
        "description": "",
        "images": [
            "images/tools/prod/8 - 7in1 Hub/main_images/main-image-1.jpeg",
            "images/tools/prod/8 - 7in1 Hub/main_images/main-image-10.jpeg",
            "images/tools/prod/8 - 7in1 Hub/main_images/main-image-2.jpeg",
            "images/tools/prod/8 - 7in1 Hub/main_images/main-image-3.jpeg",
            "images/tools/prod/8 - 7in1 Hub/main_images/main-image-4.jpeg",
            "images/tools/prod/8 - 7in1 Hub/main_images/main-image-5.jpeg",
            "images/tools/prod/8 - 7in1 Hub/main_images/main-image-6.jpeg",
            "images/tools/prod/8 - 7in1 Hub/main_images/main-image-7.jpeg",
            "images/tools/prod/8 - 7in1 Hub/main_images/main-image-8.jpeg",
            "images/tools/prod/8 - 7in1 Hub/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005009740373842.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 40,
        "name": "Universal Power Strip TypeC USB Port Outlet Power Strip 2M Extension Cord AC Power Socket Charge Electrical Socket EU US UK Plug",
        "category": "Productivity",
        "productStore": "3C Featured Store",
        "basePrice": 14565.47,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nMaterial: Plastic\nBacklight/Indication: Yes",
        "description": "",
        "images": [
            "https://ae-pic-a1.aliexpress-media.com/kf/S04209fe1def84ff898ef351aca02cee66.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sea69baf136db47af9b228f3187aa52dbs.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S6d4cb306731548cd87fd22568accb423o.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S76d1620dd00a43dda02366daf50efc82N.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sd0868ee8dee7401b842ba00170af54e1h.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S3767a63eba1c4d05b7a6c73edf9626ab1.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sdaba6e2bf21d4acda99fbd59172cca380.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S0b26e0cbb88142aabb0c19fb583f28c9V.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sff2e6f3865f34d90a50cedafb9e9acffH.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S115a9cf1e5484c278e753cfe444d18b7M.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sf25a447479fc44da8cb8de3f2f197dd0G.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sa362bf6b43b44efd84eff1347b585667o.jpg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005008363648185.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 41,
        "name": "Toocki Retractable 100W USB C to USB C Cable Fast Charging for iPhone 16 15 Pro Max Samsung S24 S23 Xiaomi Macbook Type C Cable",
        "category": "Productivity",
        "productStore": "toocki Direct Official Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae-pic-a1.aliexpress-media.com/kf/S7da057dcd6e8423da216398874e6dcdbb.png",
        "brief": "High-concerned chemical: None\nMaterial: Braid\nConnector B: Type-C",
        "description": "",
        "images": [
            "https://ae-pic-a1.aliexpress-media.com/kf/S3471f198a8014258a39916a1115044523.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S70a0851aa7ae4718a0f75692733464c0f.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S96df5f16bec84d31a4a18929831cccec3.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S0e66a54ec0664d5eb25afd7cdeb345d1o.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sa81ea5a497a040b7a4608784b6ec84f1o.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sbc070a2b98774cd9b36d1ea01bd91e010.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sa8436c2f4401415493b76e1982840abag.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S013c5941ea47425e94f591403920bda4e.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S848b40926e254746b8113fd74664a98aM.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Scafe741de8ce47ff9b44f3cbdcf4dee2K.jpg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005008664315126.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 42,
        "name": "Toocki 100W 3 in 1 USB Cale Micro USB Type C Lighting Charging Cable for iPhone 15 14 Samsung Galaxy S24 S23 Xiaomi Huawei POCO",
        "category": "Productivity",
        "productStore": "toocki Direct Official Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae-pic-a1.aliexpress-media.com/kf/S7da057dcd6e8423da216398874e6dcdbb.png",
        "brief": "High-concerned chemical: None\nMaterial: Braid\nMaximum Current: 3A",
        "description": "",
        "images": [
            "images/tools/prod/11 - data cable/main_images/main-image-1.jpeg",
            "images/tools/prod/11 - data cable/main_images/main-image-2.jpeg",
            "images/tools/prod/11 - data cable/main_images/main-image-3.jpeg",
            "images/tools/prod/11 - data cable/main_images/main-image-4.jpeg",
            "images/tools/prod/11 - data cable/main_images/main-image-5.jpeg",
            "images/tools/prod/11 - data cable/main_images/main-image-6.jpeg",
            "images/tools/prod/11 - data cable/main_images/main-image-7.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005006238651854.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 43,
        "name": "UGREEN XLR to 3.5mm Microphone Audio HiFi Cable XLR Female to Mini Jack Aux Mic Cord for Camcorders DSLR Cameras Computer",
        "category": "Productivity",
        "productStore": "Ugreen Official Store",
        "basePrice": 15037.16,
        "shipping": 4932.57,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae-pic-a1.aliexpress-media.com/kf/S7da057dcd6e8423da216398874e6dcdbb.png",
        "brief": "High-concerned chemical: None\nFeature: None\nBundle: Bundle 1",
        "description": "",
        "images": [
            "images/tools/prod/12 - aux cable/main_images/main-image-1.jpeg",
            "images/tools/prod/12 - aux cable/main_images/main-image-2.jpeg",
            "images/tools/prod/12 - aux cable/main_images/main-image-3.jpeg",
            "images/tools/prod/12 - aux cable/main_images/main-image-4.jpeg",
            "images/tools/prod/12 - aux cable/main_images/main-image-5.jpeg",
            "images/tools/prod/12 - aux cable/main_images/main-image-6.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005002326928724.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 44,
        "name": "5Pcs 3.5mm 6.35mm Stereo Mono Plug To 3.5mm 6.5mm Audio Jack Connector Adapter Converter for Speaker",
        "category": "Productivity",
        "productStore": "Shop1104463140 Store",
        "basePrice": 3589.74,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nVoltage: None\nOrigin: Mainland China",
        "description": "",
        "images": [
            "images/tools/prod/13 - Aux Adapt/variant_images/variant-image-1.jpeg",
            "images/tools/prod/13 - Aux Adapt/variant_images/variant-image-10.jpeg",
            "images/tools/prod/13 - Aux Adapt/variant_images/variant-image-11.jpeg",
            "images/tools/prod/13 - Aux Adapt/variant_images/variant-image-12.jpeg",
            "images/tools/prod/13 - Aux Adapt/variant_images/variant-image-13.jpeg",
            "images/tools/prod/13 - Aux Adapt/variant_images/variant-image-14.jpeg",
            "images/tools/prod/13 - Aux Adapt/variant_images/variant-image-15.jpeg",
            "images/tools/prod/13 - Aux Adapt/variant_images/variant-image-16.jpeg",
            "images/tools/prod/13 - Aux Adapt/variant_images/variant-image-17.jpeg",
            "images/tools/prod/13 - Aux Adapt/variant_images/variant-image-18.jpeg",
            "images/tools/prod/13 - Aux Adapt/variant_images/variant-image-2.jpeg",
            "images/tools/prod/13 - Aux Adapt/variant_images/variant-image-3.jpeg",
            "images/tools/prod/13 - Aux Adapt/variant_images/variant-image-4.jpeg",
            "images/tools/prod/13 - Aux Adapt/variant_images/variant-image-5.jpeg",
            "images/tools/prod/13 - Aux Adapt/variant_images/variant-image-6.jpeg",
            "images/tools/prod/13 - Aux Adapt/variant_images/variant-image-7.jpeg",
            "images/tools/prod/13 - Aux Adapt/variant_images/variant-image-8.jpeg",
            "images/tools/prod/13 - Aux Adapt/variant_images/variant-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005009263892393.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 45,
        "name": "High-quality Hard Drive 2TB High-speed External Hd 128TB 64TB Portable SSD USB3.1 Solid State Disk for Mac/ Pc/Laptops/Phones",
        "category": "Productivity",
        "productStore": "Shop1105087146 Store",
        "basePrice": 11613.66,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "Cooling Fin: Yes\nHigh-concerned chemical: None\nInterface Type: SATA 3.0",
        "description": "",
        "images": [
            "images/tools/prod/14 - ssd1Tb/main_images/main-image-1.jpeg",
            "images/tools/prod/14 - ssd1Tb/main_images/main-image-10.jpeg",
            "images/tools/prod/14 - ssd1Tb/main_images/main-image-11.jpeg",
            "images/tools/prod/14 - ssd1Tb/main_images/main-image-12.jpeg",
            "images/tools/prod/14 - ssd1Tb/main_images/main-image-13.jpeg",
            "images/tools/prod/14 - ssd1Tb/main_images/main-image-14.jpeg",
            "images/tools/prod/14 - ssd1Tb/main_images/main-image-15.jpeg",
            "images/tools/prod/14 - ssd1Tb/main_images/main-image-2.jpeg",
            "images/tools/prod/14 - ssd1Tb/main_images/main-image-3.jpeg",
            "images/tools/prod/14 - ssd1Tb/main_images/main-image-4.jpeg",
            "images/tools/prod/14 - ssd1Tb/main_images/main-image-5.jpeg",
            "images/tools/prod/14 - ssd1Tb/main_images/main-image-6.jpeg",
            "images/tools/prod/14 - ssd1Tb/main_images/main-image-7.jpeg",
            "images/tools/prod/14 - ssd1Tb/main_images/main-image-8.jpeg",
            "images/tools/prod/14 - ssd1Tb/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005010488128349.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 46,
        "name": "ADATA UV150 USB3.2 High-speed Flash Usb Flash Drive Plug And Play Easy Portable USB Flash Drive Black 256GB 128GB 64GB 32GB",
        "category": "Productivity",
        "productStore": "Little Donald Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nEncryption: No\nPackage: Yes",
        "description": "",
        "images": [
            "images/tools/prod/15 - flash/main_images/main-image-1 (1).jpeg",
            "images/tools/prod/15 - flash/main_images/main-image-1.jpeg",
            "images/tools/prod/15 - flash/main_images/main-image-2 (1).jpeg",
            "images/tools/prod/15 - flash/main_images/main-image-2.jpeg",
            "images/tools/prod/15 - flash/main_images/main-image-3 (1).jpeg",
            "images/tools/prod/15 - flash/main_images/main-image-3.jpeg",
            "images/tools/prod/15 - flash/main_images/main-image-4 (1).jpeg",
            "images/tools/prod/15 - flash/main_images/main-image-4.jpeg",
            "images/tools/prod/15 - flash/main_images/main-image-5 (1).jpeg",
            "images/tools/prod/15 - flash/main_images/main-image-5.jpeg",
            "images/tools/prod/15 - flash/main_images/main-image-6 (1).jpeg",
            "images/tools/prod/15 - flash/main_images/main-image-6.jpeg",
            "images/tools/prod/15 - flash/main_images/main-image-7 (1).jpeg",
            "images/tools/prod/15 - flash/main_images/main-image-7.jpeg",
            "images/tools/prod/15 - flash/main_images/main-image-8.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005005951301259.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 47,
        "name": "Portable Scale Digital LCD Display 110lb/50kg Electronic Luggage Hanging Suitcase Travel Weighs Baggage Bag Weight Balance Tools",
        "category": "Productivity",
        "productStore": "DIDA BEAR Official Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": true,
        "isEssential": false,
        "essentialRank": 1,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nCertification: CE\nItem Type: TRAVEL ACCESSORIES",
        "description": "",
        "images": [
            "images/tools/prod/16 - hand scale/main_images/main-image-1.jpeg",
            "images/tools/prod/16 - hand scale/main_images/main-image-2.jpeg",
            "images/tools/prod/16 - hand scale/main_images/main-image-3.jpeg",
            "images/tools/prod/16 - hand scale/main_images/main-image-5.jpeg",
            "images/tools/prod/16 - hand scale/main_images/main-image-6.jpeg",
            "images/tools/prod/16 - hand scale/main_images/main-image-7.jpeg",
            "images/tools/prod/16 - hand scale/main_images/main-image-8.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005005562814968.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 48,
        "name": "10/20/50PCS Cable Organizer Clips Wire Winder Holder Protector USB Cable Management Adhesive Hooks Desk Clamp For Home Office",
        "category": "Productivity",
        "productStore": "Mosizave 3C Accessories Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nFeatures: Cable Clip\nMaterial: Acrylic",
        "description": "",
        "images": [
            "images/tools/prod/17 - organiser/variant_images/variant-image-1.jpeg",
            "images/tools/prod/17 - organiser/variant_images/variant-image-10.jpeg",
            "images/tools/prod/17 - organiser/variant_images/variant-image-2.jpeg",
            "images/tools/prod/17 - organiser/variant_images/variant-image-3.jpeg",
            "images/tools/prod/17 - organiser/variant_images/variant-image-4.jpeg",
            "images/tools/prod/17 - organiser/variant_images/variant-image-5.jpeg",
            "images/tools/prod/17 - organiser/variant_images/variant-image-6.jpeg",
            "images/tools/prod/17 - organiser/variant_images/variant-image-7.jpeg",
            "images/tools/prod/17 - organiser/variant_images/variant-image-8.jpeg",
            "images/tools/prod/17 - organiser/variant_images/variant-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005008222543759.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 49,
        "name": "New HYUNDAI X1PRO Wireless Bluetooth 6.0 Headphone,AI Translation Earphones,100+Languages,With Magnetic Touch Control LED Screen",
        "category": "Productivity",
        "productStore": "Lenovo ThinkPlus LivePods Store",
        "basePrice": 45592.97,
        "shipping": 0,
        "isEssential": true,
        "essentialRank": 4,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nMaterial: Plastic\nBattery Capacity[mAh]: 400",
        "description": "",
        "images": [
            "images/tools/prod/18 - heaadphones/main_images/main-image-1.jpeg",
            "images/tools/prod/18 - heaadphones/main_images/main-image-2.jpeg",
            "images/tools/prod/18 - heaadphones/main_images/main-image-3.jpeg",
            "images/tools/prod/18 - heaadphones/main_images/main-image-4.jpeg",
            "images/tools/prod/18 - heaadphones/main_images/main-image-5.jpeg",
            "images/tools/prod/18 - heaadphones/main_images/main-image-6.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005010441711589.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 50,
        "name": "CD12 S11 Ultra Smartwatch Android 12.0 5G LTE Sim Card Rotary Camera 2.26 inch Amoled 490*580 HD Screen 2080Mah Smart Watch Men",
        "category": "Productivity",
        "productStore": "Global Version Smart Watch Store",
        "basePrice": 73126.45,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nVoice assistant built-in: No\nBluetooth-compatible Version: 4.2",
        "description": "",
        "images": [
            "https://ae-pic-a1.aliexpress-media.com/kf/S8c4a3bd0eba7434daa21036f7fbcf6c0F.png",
            "https://ae-pic-a1.aliexpress-media.com/kf/S8c4a3bd0eba7434daa21036f7fbcf6c0F.png",
            "https://ae-pic-a1.aliexpress-media.com/kf/S4f4c0f85fedf4559ac487a0e0b16456dH.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S6ab25f8702764749ae7db121b102008eY.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S5ecc5d110074423ba7bf61c31d90d9a2U.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S40101cfd72a04b2d9178194ba6159712U.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S655e9cc492794bb8abd8f4ed8c8911927.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S6ab25f8702764749ae7db121b102008eY.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sdb78586045c747afa6291b03ba7029dfr.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/S8a655b1728944ae4bff96f04d5c3fe7ew.jpg",
            "https://ae-pic-a1.aliexpress-media.com/kf/Sa74ea59e8a9846558cab2e2c69b0dd5bE.jpg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005010505568095.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 51,
        "name": "HOT 2026 New Pad Camon 40 Pro Tablet PC 7.3inch HD Android 15 16GB+1TB 7800mAh Battery 4G 5G Dual Sim Card WiFi GPS Google Tab",
        "category": "Productivity",
        "productStore": "Shop1105230033 Store",
        "basePrice": 85362.59,
        "shipping": 34685.96,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "None",
        "brief": "High-concerned chemical: None\nMaterial: POLYESTER\nStyle: Fasion",
        "description": "",
        "images": [
            "images/tools/prod/20 - phone/main_images/main-image-1.jpeg",
            "images/tools/prod/20 - phone/main_images/main-image-10.jpeg",
            "images/tools/prod/20 - phone/main_images/main-image-2.jpeg",
            "images/tools/prod/20 - phone/main_images/main-image-3.jpeg",
            "images/tools/prod/20 - phone/main_images/main-image-4.jpeg",
            "images/tools/prod/20 - phone/main_images/main-image-5.jpeg",
            "images/tools/prod/20 - phone/main_images/main-image-7.jpeg",
            "images/tools/prod/20 - phone/main_images/main-image-8.jpeg",
            "images/tools/prod/20 - phone/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005010392952424.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 52,
        "name": "Portable Sport Clip Mini Walkman 1.8-inch MP3 player Bluetooth 5.2 MP4 music player supports e-books/recorders/FM radios/clocks",
        "category": "Productivity",
        "productStore": "3C Digital Lab Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "None",
        "brief": "High-concerned chemical: None\nStreaming Service Compatibility: Other\nCompatible Devices: Others",
        "description": "",
        "images": [
            "images/tools/prod/21 - mp3/main_images/main-image-1 (1).jpeg",
            "images/tools/prod/21 - mp3/main_images/main-image-1.jpeg",
            "images/tools/prod/21 - mp3/main_images/main-image-10.jpeg",
            "images/tools/prod/21 - mp3/main_images/main-image-11.jpeg",
            "images/tools/prod/21 - mp3/main_images/main-image-12.jpeg",
            "images/tools/prod/21 - mp3/main_images/main-image-2.jpeg",
            "images/tools/prod/21 - mp3/main_images/main-image-3.jpeg",
            "images/tools/prod/21 - mp3/main_images/main-image-4.jpeg",
            "images/tools/prod/21 - mp3/main_images/main-image-5.jpeg",
            "images/tools/prod/21 - mp3/main_images/main-image-6.jpeg",
            "images/tools/prod/21 - mp3/main_images/main-image-7.jpeg",
            "images/tools/prod/21 - mp3/main_images/main-image-8.jpeg",
            "images/tools/prod/21 - mp3/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005006305418939.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 53,
        "name": "Lafitear LD4 Wired In Ear Dynamic Earphone Bass Surround Stereo Headphone 3.5mm USB C HIFI Sports Music Headset Detachable Cable",
        "category": "Productivity",
        "productStore": "DISOUR 3C Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": true,
        "isEssential": false,
        "essentialRank": 7,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nMaterial: ABS,Plastic\nCategory: Earphones & Headphones",
        "description": "",
        "images": [
            "images/tools/prod/22 - erapiece/main_images/main-image-1.jpeg",
            "images/tools/prod/22 - erapiece/main_images/main-image-10.jpeg",
            "images/tools/prod/22 - erapiece/main_images/main-image-11.jpeg",
            "images/tools/prod/22 - erapiece/main_images/main-image-12.jpeg",
            "images/tools/prod/22 - erapiece/main_images/main-image-2.jpeg",
            "images/tools/prod/22 - erapiece/main_images/main-image-3.jpeg",
            "images/tools/prod/22 - erapiece/main_images/main-image-4.jpeg",
            "images/tools/prod/22 - erapiece/main_images/main-image-5.jpeg",
            "images/tools/prod/22 - erapiece/main_images/main-image-6.jpeg",
            "images/tools/prod/22 - erapiece/main_images/main-image-7.jpeg",
            "images/tools/prod/22 - erapiece/main_images/main-image-8.jpeg",
            "images/tools/prod/22 - erapiece/main_images/main-image-9.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005008423488294.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 54,
        "name": "300Mbps Wireless WIFI Repeater 2.4G Router Wifi Range Extender Wi-Fi Signal Amplifier 802.11N Network Card Adapter for PC",
        "category": "Productivity",
        "productStore": "Ya Ya 3C Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": true,
        "essentialRank": 6,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "Frequency Band Class: Single-Band\nHigh-concerned chemical: None\nWireless Communication Standard: 802.11.a",
        "description": "",
        "images": [
            "images/tools/prod/23 - wifi extend/main_images/main-image-1 (1).jpeg",
            "images/tools/prod/23 - wifi extend/main_images/main-image-1.jpeg",
            "images/tools/prod/23 - wifi extend/main_images/main-image-2 (1).jpeg",
            "images/tools/prod/23 - wifi extend/main_images/main-image-2.jpeg",
            "images/tools/prod/23 - wifi extend/main_images/main-image-3 (1).jpeg",
            "images/tools/prod/23 - wifi extend/main_images/main-image-3.jpeg",
            "images/tools/prod/23 - wifi extend/main_images/main-image-4 (1).jpeg",
            "images/tools/prod/23 - wifi extend/main_images/main-image-4.jpeg",
            "images/tools/prod/23 - wifi extend/main_images/main-image-5 (1).jpeg",
            "images/tools/prod/23 - wifi extend/main_images/main-image-5.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005007098505150.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 55,
        "name": "Eaget TFCG Memory Card 512GB 256GB 128GB 32GB TF SD Card Class10 UHS-1 Flash Card Memory 64GB 32GB SD Card",
        "category": "Productivity",
        "productStore": "Storage Franchise Store",
        "basePrice": 12269.78,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nApplication: High Speed Read and Write,MOBILE PHONE,Tablet,NOTEBOOK,Tachograph,Camera,Monitoring,Speakers,Digital Devices,Robot,UAV,File Storage\nApplication Performance Class: A1",
        "description": "",
        "images": [
            "images/tools/prod/24 - sd card/main_images/main-image-1.jpeg",
            "images/tools/prod/24 - sd card/main_images/main-image-2.jpeg",
            "images/tools/prod/24 - sd card/main_images/main-image-3.jpeg",
            "images/tools/prod/24 - sd card/main_images/main-image-4.jpeg",
            "images/tools/prod/24 - sd card/main_images/main-image-5.jpeg",
            "images/tools/prod/24 - sd card/main_images/main-image-6.jpeg",
            "images/tools/prod/24 - sd card/main_images/main-image-7.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005006313120809.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 56,
        "name": "5 Ports USB C PD Charger Quick Charge 3.0 Type C USB Phone Chargers Fast Charging Adapter For iPhone 16 15 Samsung Xiaomi Huawei",
        "category": "Productivity",
        "productStore": "Shop911551365 Store",
        "basePrice": 1580.34,
        "shipping": 0,
        "isEssential": false,
        "essentialRank": 0,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nApplied Fast Charge Protocols: Qualcomm Quick Charge\nGaN: Yes",
        "description": "",
        "images": [
            "images/tools/prod/25 - brick/variant_images/variant-image-1.jpeg",
            "images/tools/prod/25 - brick/variant_images/variant-image-2.jpeg",
            "images/tools/prod/25 - brick/variant_images/variant-image-3.jpeg",
            "images/tools/prod/25 - brick/variant_images/variant-image-4.jpeg",
            "images/tools/prod/25 - brick/variant_images/variant-image-5.jpeg",
            "images/tools/prod/25 - brick/variant_images/variant-image-6.jpeg",
            "images/tools/prod/25 - brick/variant_images/variant-image-7.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005009753118830.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 57,
        "name": "HiFi 16-300Ω Headphone Amplifier 3.5mm Audio Amplifier Stereo Adjustable Headphone Volume Amplifier With two-stage gain switch",
        "category": "Productivity",
        "productStore": "MnnWuu Official Store",
        "basePrice": 2633.9,
        "shipping": 0,
        "isEssential": true,
        "isEssential": false,
        "essentialRank": 8,
        "dealTag": "https://ae01.alicdn.com/kf/S16183c3f12904fbbaf3f8aef523f0b73T.png",
        "brief": "High-concerned chemical: None\nBluetooth: Yes\nModel Number: HiFi Headphone Amplifier",
        "description": "",
        "images": [
            "images/tools/prod/25 - headphone amp/main_images/main-image-1.jpeg",
            "images/tools/prod/25 - headphone amp/main_images/main-image-2.jpeg",
            "images/tools/prod/25 - headphone amp/main_images/main-image-3.jpeg",
            "images/tools/prod/25 - headphone amp/main_images/main-image-4.jpeg",
            "images/tools/prod/25 - headphone amp/main_images/main-image-5.jpeg",
            "images/tools/prod/25 - headphone amp/main_images/main-image-6.jpeg",
            "images/tools/prod/25 - headphone amp/main_images/main-image-7.jpeg"
        ],
        "productLink": "https://www.aliexpress.com/item/1005009240121841.html",
        "quantity": 1,
        "source": "AliExpress"
    },
    {
        "id": 58,
        "name": "Hostinger Cloud Startup Plan - Optimized for business and ecommerce websites",
        "category": "Productivity",
        "productStore": "Hostinger",
        "basePrice": 155906.40,
        "shipping": 0,
        "isEssential": true,
        "essentialRank": 2,
        "dealTag": "New yera's Sale - 75% OFF",
        "brief": "10 Node.js web apps\n2 CPU Cores4 GB RAM\n100 GB NVMe Storage\n2 000 000 Files and Directories (Inodes)\n100 PHP Workers\n100 Websites ",
        "description": "30-day money-back guarantee\nDomain included\nFree\nUnlimited SSL\nFree\n10 mailboxes per website - free for 1 year\nFree\nManaged hosting for WordPress and WooCommerce\nCDN included\nDedicated IP address\nPriority 24/7 expert support\nNew",
        "images": [
            "images/tools/prod/25 - headphone amp/main_images/main-image-1.jpeg",
            "images/tools/prod/25 - headphone amp/main_images/main-image-2.jpeg",
            "images/tools/prod/25 - headphone amp/main_images/main-image-3.jpeg",
            "images/tools/prod/25 - headphone amp/main_images/main-image-4.jpeg",
            "images/tools/prod/25 - headphone amp/main_images/main-image-5.jpeg",
            "images/tools/prod/25 - headphone amp/main_images/main-image-6.jpeg",
            "images/tools/prod/25 - headphone amp/main_images/main-image-7.jpeg"
        ],
        "productLink": "https://hpanel.hostinger.com/buy-hosting",
        "quantity": 1,
        "source": "Hostinger"
    }
];